language: python
ps: linux
dist: centos7
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
#virtualenv:
#  system_site_packages: true
install:
  - pip install -r requirements.txt
script:
  - pytest main.py