language: python
python:
  - 3.5
  - 3.9
env:
  - PARALLELIZE=true
  - PARALLELIZE=false
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r requirements.txt
script: pytest main.py
before_deploy:
  - pyinstaller "main.py"
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: dist/*.x86_64
  skip_cleanup: true
  draft: true
  on:
    tags: true
