language: python
python:
  - 2.7
  - 3.5
  - 3.9
env:
  - PARALLELIZE=true
  - PARALLELIZE=false
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r requirements.txt
script: pytest main.py
